# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
newsheet "Sheet2"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
label A0 = "Sheet 1"
label A1 = "Four"
let B1 = 4
label A2 = "Five"
let B2 = 5
label A3 = "Six"
let B3 = 6
let B4 = @sum(B1:B3)
goto A1
movetosheet "Sheet2"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
label A0 = "Sheet 2"
label A1 = "One"
let B1 = 1
label A2 = "Two"
let B2 = 2
label A3 = "Three"
let B3 = 3
goto A0
movetosheet "Sheet1"
