# This data file was generated by the Spreadsheet Calculator Improvised (sc-im)
# You almost certainly shouldn't edit it.

newsheet "Sheet1"
movetosheet "Sheet1"
offscr_sc_cols 0
offscr_sc_rows 0
nb_frozen_rows 0
nb_frozen_cols 0
nb_frozen_screenrows 0
nb_frozen_screencols 0
format B 13 2 0
label A0 = "test 1"
leftstring B0 = "left aligned"
label A1 = "test 2"
rightstring B1 = "right aligned"
label A2 = "test 3"
label B2 = "center"
goto B2
movetosheet "Sheet1"
